In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("/home/saroj/Desktop/Python for Machine Learning and Data Science/Week 05/Day 04/Datas/weather_data - weather_data.csv",skiprows = 1)
print(data)

   dfuhsdjufio     Unnamed: 1    Unnamed: 2 Unnamed: 3
0          day    temperature     windspeed      event
1     1/1/2017             32             6       Rain
2     1/4/2017  not available             9      Sunny
3     1/5/2017             -1  not measured       Snow
4     1/6/2017  not available             7   no event
5     1/7/2017             32  not measured       Rain
6     1/8/2017  not available  not measured      Sunny
7     1/9/2017  not available  not measured   no event
8    1/10/2017             34             8     Cloudy
9    1/11/2017             -4            -1       Snow
10   1/12/2017             26            12      Sunny
11   1/13/2017             12            12      Rainy
12   1/11/2017             -1            12       Snow
13   1/14/2017             40            -1      Sunny

In [2]:
data = pd.read_csv("/home/saroj/Desktop/Python for Machine Learning and Data Science/Week 05/Day 04/Datas/weather_data - weather_data.csv",header = 2)
print(data)

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

# Reading a csv file without header and giving names to the columns

In [7]:
import pandas as pd

# Assuming you have your column names in a list named 'column_names'
column_names = ['Day','Temperature','WinndSpeed','Event']

# Reading the CSV file
Weather_df = pd.read_csv("/home/saroj/Desktop/Python for Machine Learning and Data Science/Week 05/Day 04/Datas/weather_data - weather_data.csv", skiprows=3, header=None, names=column_names)

Weather_df

          Day    Temperature    WinndSpeed     Event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

# Read limited data from csv file using nrows parameters

In [9]:
Weather_df = pd.read_csv("/home/saroj/Desktop/Python for Machine Learning and Data Science/Week 05/Day 04/Datas/weather_data - weather_data.csv", skiprows=3,nrows=3, header=None, names=column_names)

Weather_df

        Day    Temperature    WinndSpeed  Event
0  1/1/2017             32             6   Rain
1  1/4/2017  not available             9  Sunny
2  1/5/2017             -1  not measured   Snow

# Reading a CSV file with na_value parameters('Weather_data.csv' file)

In [15]:
Weather_df = pd.read_csv("/home/saroj/Desktop/Python for Machine Learning and Data Science/Week 05/Day 04/Datas/weather_data - weather_data.csv",skiprows=2, na_values="not available")

Weather_df

          day  temperature     windspeed     event
0    1/1/2017         32.0             6      Rain
1    1/4/2017          NaN             9     Sunny
2    1/5/2017         -1.0  not measured      Snow
3    1/6/2017          NaN             7  no event
4    1/7/2017         32.0  not measured      Rain
5    1/8/2017          NaN  not measured     Sunny
6    1/9/2017          NaN  not measured  no event
7   1/10/2017         34.0             8    Cloudy
8   1/11/2017         -4.0            -1      Snow
9   1/12/2017         26.0            12     Sunny
10  1/13/2017         12.0            12     Rainy
11  1/11/2017         -1.0            12      Snow
12  1/14/2017         40.0            -1     Sunny